/// <reference no-default-lib="true"/>
/// <reference lib="es2015"/>
/// <reference path="./BlockEvent/BreakEvent.lib.d.ts" />
/// <reference path="./BlockEvent/ClickedEvent.lib.d.ts" />
/// <reference path="./BlockEvent/CollidedEvent.lib.d.ts" />
/// <reference path="./BlockEvent/DoorToggleEvent.lib.d.ts" />
/// <reference path="./BlockEvent/EntityFallenUponEvent.lib.d.ts" />
/// <reference path="./BlockEvent/ExplodedEvent.lib.d.ts" />
/// <reference path="./BlockEvent/HarvestedEvent.lib.d.ts" />
/// <reference path="./BlockEvent/InitEvent.lib.d.ts" />
/// <reference path="./BlockEvent/InteractEvent.lib.d.ts" />
/// <reference path="./BlockEvent/NeighborChangedEvent.lib.d.ts" />
/// <reference path="./BlockEvent/RainFillEvent.lib.d.ts" />
/// <reference path="./BlockEvent/RedstoneEvent.lib.d.ts" />
/// <reference path="./BlockEvent/TimerEvent.lib.d.ts" />
/// <reference path="./BlockEvent/UpdateEvent.lib.d.ts" />