#!/bin/bash

rm -rf ./bundle
mkdir ./bundle
rm -rf ./dist
mkdir ./dist
rm -rf ./built
mkdir ./built

# bundle src/index
deno cache ./src/testBlock.ts
deno bundle ./src/testBlock.ts ./bundle/testBlock.js
# bundle src/RegenBlock/script
deno cache ./src/RegenBlock/script.ts
deno bundle ./src/RegenBlock/script.ts ./bundle/RegenBlock.js


npx babel bundle -d built

deno --unstable run -A ./cjs-to-raw.ts