#!/bin/bash

rm -rf ./bundle
mkdir ./bundle
mkdir ./bundle/toolkit
mkdir ./bundle/settings-tree
rm -rf ./dist
mkdir ./dist
rm -rf ./built
mkdir ./built

# bundle src/index
deno cache ./src/testBlock.ts
deno bundle ./src/testBlock.ts ./bundle/testBlock.js
# bundle src/RegenBlock/script
deno cache ./src/RegenBlock/script.ts
deno bundle ./src/RegenBlock/script.ts ./bundle/RegenBlock.js
# bundle src/toolkit/block_details
deno cache ./src/toolkit/block_details.ts
deno bundle ./src/toolkit/block_details.ts ./bundle/toolkit/block_details.js
# bundle src/settings-tree/global
deno cache ./src/settings-tree/global.ts
deno bundle ./src/settings-tree/global.ts ./bundle/settings-tree/global.js


npx babel bundle -d built

deno --unstable run -A ./cjs-to-raw.ts